name: github io page
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: download code
        uses: actions/checkout@v4
      - name: install dependencias
        run: npm install 
      - name: run tests
        run: npm run test
      - name: build application
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: public
  notification:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ failure() }}
    steps:
      - name: failure notification
        run: echo "send failure notificatiopn"
    
      
        
        
