name: github io page
on: push
jobs:
  installation:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: download code
        uses: actions/checkout@v4
      - name: install dependencias
        run: npm install 
      
        
        
