name: github io page
on: push
jobs:
  installation:
    runs-on: ubuntu-latest
    steps:
      - name: debug variable
        run: echo "${{ secrets.TOKEN_SECRET }}"
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
        
