name: github io page
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: download code
        uses: actions/checkout@v4
      - name: install dependencias
        run: npm install 
      - name: run tests
        run: npm run test
  notification:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ failure() }}
    steps:
      - name: failure notification
        run: echo "send failure notificatiopn"
    
      
        
        
