name: github io page
on: push
jobs:
  installation:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: install redis cli
        run: apt-get update -y && apt-get install redis-tools -y
      - name: test redis
        run: redlis-cli -h localhost -p 6379 ping
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: download code
        uses: actions/checkout@v4
        
